//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dossier
    {
        public long dossier_id { get; set; }
        public Nullable<long> utilisateur_id { get; set; }
        public Nullable<bool> certificat_medical { get; set; }
        public Nullable<bool> fiche_renseignement { get; set; }
        public Nullable<bool> assurance { get; set; }
        public Nullable<bool> paiement { get; set; }
        public Nullable<bool> dossier_complet { get; set; }
    
        public virtual utilisateur utilisateur { get; set; }
    }
}
