//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seance
    {
        public long seance_id { get; set; }
        public Nullable<long> lieu_id { get; set; }
        public Nullable<long> encadrant_id { get; set; }
        public string jour { get; set; }
        public Nullable<System.TimeSpan> heure_debut { get; set; }
        public Nullable<System.TimeSpan> heure_fin { get; set; }
        public Nullable<long> section_id { get; set; }
    
        public virtual lieu lieu { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        public virtual section section { get; set; }
    }
}
