//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAsso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public section()
        {
            this.participe = new HashSet<participe>();
            this.seance = new HashSet<seance>();
        }
    
        public long section_id { get; set; }
        public Nullable<long> discipline_id { get; set; }
        public string section_nom { get; set; }
        public Nullable<long> encadrant_id { get; set; }
        public Nullable<int> nbParticipant { get; set; }
        public Nullable<int> places_max { get; set; }
        public string prix { get; set; }
        public string description { get; set; }
    
        public virtual discipline discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participe> participe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seance> seance { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
